export const dummies = [
  {
    key: '1',
    orderId: 'CM9801',
    user: { name: 'Natali Craig', avatar: 'N' },
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: { text: 'In Progress', color: '#1890ff' },
  },
  {
    key: '2',
    orderId: 'CM9802',
    user: { name: 'Kate Morrison', avatar: 'K' },
    project: 'CRM Admin pages',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: { text: 'Complete', color: '#52c41a' },
  },
  {
    key: '3',
    orderId: 'CM9803',
    user: { name: 'Drew Cano', avatar: 'D' },
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: { text: 'Pending', color: '#87ceeb' },
  },
  {
    key: '4',
    orderId: 'CM9804',
    user: { name: 'Orlando Diggs', avatar: 'O' },
    project: 'Admin Dashboard',
    address: 'Washburn Baton Rouge',
    date: 'Yesterday',
    status: { text: 'Approved', color: '#faad14' },
  },
  {
    key: '5',
    orderId: 'CM9805',
    user: { name: 'Andi Lane', avatar: 'A' },
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: { text: 'Rejected', color: '#d9d9d9' },
  },
  {
    key: '6',
    orderId: 'CM9801',
    user: { name: 'Natali Craig', avatar: 'N' },
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: { text: 'In Progress', color: '#1890ff' },
  },
  {
    key: '7',
    orderId: 'CM9802',
    user: { name: 'Kate Morrison', avatar: 'K' },
    project: 'CRM Admin pages',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: { text: 'Complete', color: '#52c41a' },
  },
  {
    key: '8',
    orderId: 'CM9803',
    user: { name: 'Drew Cano', avatar: 'D' },
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: { text: 'Pending', color: '#87ceeb' },
  },
  {
    key: '9',
    orderId: 'CM9804',
    user: { name: 'Orlando Diggs', avatar: 'O' },
    project: 'Admin Dashboard',
    address: 'Washburn Baton Rouge',
    date: 'Yesterday',
    status: { text: 'Approved', color: '#faad14' },
  },
  {
    key: '10',
    orderId: 'CM9805',
    user: { name: 'Andi Lane', avatar: 'A' },
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: { text: 'Rejected', color: '#d9d9d9' },
  },
];
